In [3]:
! pip install numpy

You should consider upgrading via the 'pip install --upgrade pip' command.


In [4]:
import numpy as np

In [5]:
l1 = [1,2,3]
l2 = [4,5,6]

In [6]:
l1+l2

[1, 2, 3, 4, 5, 6]

In [7]:
ar1 = np.array(l1)
ar2 = np.array(l2)

In [8]:
ar1

array([1, 2, 3])

In [9]:
type(ar1)

numpy.ndarray

In [10]:
ar1+ar2

array([5, 7, 9])

In [18]:
arr = np.array([[1,2,3],
                [4,5,6], 
                [7,8,9]])

In [19]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr.shape

(3, 3)

In [23]:
arr[1,2]

6

In [24]:
# Array Slicing
# arr[ rows  , cols ]

In [26]:
arr [ 0:3 , 1 ]

array([2, 5, 8])

In [29]:
4 * arr

array([[ 4,  8, 12],
       [16, 20, 24],
       [28, 32, 36]])

In [31]:
ar1

array([1, 2, 3])

In [32]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
ar1 + arr

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [38]:
5*arr

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [40]:
np.random.randint(10, 100, size= (3,3))

array([[83, 59, 88],
       [33, 95, 16],
       [90, 64, 75]])

In [42]:
np.sin(90)

0.8939966636005579

In [45]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
np.sum(arr, axis= 1)

array([ 6, 15, 24])

In [48]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [49]:
def distance(p1, p2):
    return np.sqrt(np.sum((p2-p1)**2))

In [53]:
p1 = np.array([5,5])
p2 = np.array([0,0])

In [54]:
distance(p1,p2)

7.0710678118654755